### PR TITLE
soldat: init at unstable-2020-11-26

### PR DESCRIPTION
**Pull request by sternenseemann**
Still waiting to see if my PR for `gamenetworkingsockets` gets into nixpkgs.

Was thinking about adding this to the games attrset, but it doesn't really seem well-suited for open source games atm and I didn't want to add a new module ahead of the nixgames revamp.

### CODE REVIEW

**Comment by aszlig** [comment]
Just FYI: We do have a [`buildGame` helper](https://github.com/openlab-aux/vuizvui/blob/master/pkgs/games/build-support/build-game.nix) which automatically `patchelf`s the binaries and puts the whole thing into a sandbox.

**Comment by sternenseemann** [comment]
Thanks for the hint that could be helpful!

Probably the simpler solution than figuring out why fpc messes up setting the `rpath` correctly despite building from source.

**Comment by sternenseemann** [comment]
Rebased to use `buildGame`. To facilitate this i added a new `pkgs.games.other` module. Not sure if this makes sense and there is a better solution. Does hydra even build `pkgs.games.*`? `soldat` could be built by hydra as it is open source.

Also comments on the resulting expression are welcome :)

**Comment by sternenseemann** [comment]
See <https://github.com/NixOS/nixpkgs/pull/108436>.

**Pull request closed without merging**
